import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, LockKeyhole, XCircle } from "lucide-react";
import { useState } from "react";

export default function Approvals() {
  const [notes, setNotes] = useState<Record<number, string>>({});
  const utils = trpc.useUtils();
  const approvals = trpc.agent.approvals.list.useQuery();
  const review = trpc.agent.approvals.review.useMutation({ onSuccess: () => void utils.agent.approvals.list.invalidate() });
  return <div className="mx-auto max-w-5xl space-y-6"><section className="rounded-[1.8rem] border border-[#eadbb8] bg-[#fffaf0] p-7"><div className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-2xl bg-amber-100 text-amber-800"><LockKeyhole size={21} /></span><div><p className="text-[10px] font-bold uppercase tracking-[.17em] text-amber-800">Human authority</p><h1 className="mt-2 font-serif text-4xl text-[#573e1d]">Approval queue</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#796343]">Northstar can propose a future action but cannot execute it. An approval records a review decision only; the current agent has no direct external-write tool.</p></div></div></section><div className="space-y-4">{approvals.data?.map(item => <article key={item.id} className="rounded-[1.5rem] border border-[#dce3de] bg-white p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#687f83]">Run #{item.runId} · requested {new Date(item.createdAt).toLocaleString()}</p><h2 className="mt-2 font-serif text-2xl text-[#203c42]">{item.actionSummary}</h2></div><Badge className={item.status === "pending" ? "bg-amber-100 text-amber-800" : item.status === "approved" ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-700"}>{item.status}</Badge></div><pre className="mt-4 max-h-48 overflow-auto rounded-xl bg-[#f2f6f4] p-4 text-xs leading-5 text-[#426064]">{JSON.stringify(item.proposedPayload, null, 2)}</pre>{item.status === "pending" && <><Textarea value={notes[item.id] ?? ""} onChange={event => setNotes({ ...notes, [item.id]: event.target.value })} placeholder="Reviewer note (optional)" className="mt-4 min-h-20" /><div className="mt-3 flex gap-3"><Button onClick={() => review.mutate({ approvalId: item.id, status: "approved", reviewerNote: notes[item.id] })} disabled={review.isPending} className="bg-[#176447] hover:bg-[#125237]"><CheckCircle2 className="mr-2 size-4" />Approve internal outcome</Button><Button variant="outline" onClick={() => review.mutate({ approvalId: item.id, status: "rejected", reviewerNote: notes[item.id] })} disabled={review.isPending} className="border-red-200 text-red-700 hover:bg-red-50"><XCircle className="mr-2 size-4" />Reject</Button></div></>}</article>) ?? <p className="rounded-2xl border border-dashed border-[#cfdbd5] p-10 text-center text-sm text-[#687f83]">There are no approvals in your visible queue.</p>}</div></div>;
}
