import { useAuth } from "@/_core/hooks/useAuth";
import { EvidenceEmptyState } from "@/components/EvidenceEmptyState";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Archive, CheckCircle2, FileClock, FileUp, FolderCheck, Loader2, LockKeyhole, Plus, ScrollText, UploadCloud } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

const readFile = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); });
const approvalTone: Record<string, string> = { approved: "border-[#b9ddc4] bg-[#edf8f0] text-[#348154]", archived: "border-stone-200 bg-stone-50 text-stone-500", draft: "border-amber-200 bg-amber-50 text-amber-700" };

export default function Sources() {
  const { user } = useAuth(); const isAdmin = user?.role === "admin"; const utils = trpc.useUtils();
  const sources = trpc.knowledge.sources.list.useQuery(); const documents = trpc.knowledge.documents.list.useQuery();
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [classification, setClassification] = useState<"internal" | "confidential" | "restricted">("internal"); const [accessLevel, setAccessLevel] = useState<"all_users" | "admins_only">("all_users");
  const [selectedSourceId, setSelectedSourceId] = useState(""); const [title, setTitle] = useState(""); const [file, setFile] = useState<File | null>(null); const inputRef = useRef<HTMLInputElement>(null);
  const refresh = () => { void utils.knowledge.sources.list.invalidate(); void utils.knowledge.documents.list.invalidate(); void utils.knowledge.workspace.invalidate(); };
  const createSource = trpc.knowledge.sources.create.useMutation({ onSuccess: () => { toast.success("Source created as draft. Approve it before users can retrieve from it."); setName(""); setDescription(""); refresh(); }, onError: error => toast.error(error.message) });
  const approval = trpc.knowledge.sources.setApproval.useMutation({ onSuccess: () => { toast.success("Source status updated."); refresh(); }, onError: error => toast.error(error.message) });
  const upload = trpc.knowledge.documents.upload.useMutation({ onSuccess: result => { result.status === "ready" ? toast.success(`${result.chunkCount} searchable passages are ready.`) : toast.error(result.errorMessage ?? "Document ingestion needs review."); setFile(null); setTitle(""); if (inputRef.current) inputRef.current.value = ""; refresh(); }, onError: error => toast.error(error.message) });
  const submitUpload = async () => { if (!file || !selectedSourceId) return toast.error("Choose both an approved source and a file."); if (file.size > 12 * 1024 * 1024) return toast.error("Files must be 12 MB or smaller."); try { upload.mutate({ sourceId: Number(selectedSourceId), title: title.trim() || file.name.replace(/\.[^.]+$/, ""), filename: file.name, mimeType: file.type || "application/octet-stream", base64: await readFile(file), metadata: { tags: [] } }); } catch { toast.error("The file could not be read."); } };
  const approvedSources = sources.data?.filter(source => source.approvalStatus === "approved") ?? [];
  return <div className="mx-auto max-w-[1240px] space-y-6"><section className="page-heading"><div><p className="eyebrow">Knowledge governance</p><h1>Approved sources</h1><p>Define the firm’s evidence boundaries before the agent can answer. Originals remain in secure storage; this register retains governance metadata and searchable passages.</p></div><Badge className="evidence-status-badge"><LockKeyhole className="mr-1.5 size-3" />{isAdmin ? "Administrator controls" : "Approved sources only"}</Badge></section>
    {isAdmin ? <div className="grid gap-5 lg:grid-cols-2"><Card className="evidence-panel"><CardContent className="p-6"><div className="panel-title"><span className="panel-index">01</span><div><p className="eyebrow">Source boundary</p><h2>Create a governed collection</h2></div></div><p className="panel-intro">Start in draft status. Name the source owner, access rule, and classification before any document becomes eligible for retrieval.</p><div className="mt-5 grid gap-3"><div><Label>Source name</Label><Input value={name} onChange={event => setName(event.target.value)} placeholder="e.g., Operations handbook" className="mt-1.5" /></div><div><Label>Purpose and content</Label><Textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="What trusted material belongs in this boundary?" className="mt-1.5 min-h-20" /></div><div className="grid grid-cols-2 gap-3"><div><Label>Classification</Label><Select value={classification} onValueChange={value => setClassification(value as typeof classification)}><SelectTrigger className="mt-1.5"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="internal">Internal</SelectItem><SelectItem value="confidential">Confidential</SelectItem><SelectItem value="restricted">Restricted</SelectItem></SelectContent></Select></div><div><Label>Audience</Label><Select value={accessLevel} onValueChange={value => setAccessLevel(value as typeof accessLevel)}><SelectTrigger className="mt-1.5"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all_users">All signed-in users</SelectItem><SelectItem value="admins_only">Administrators only</SelectItem></SelectContent></Select></div></div><Button onClick={() => createSource.mutate({ name, description, classification, accessLevel })} disabled={!name.trim() || createSource.isPending} className="evidence-primary-button">{createSource.isPending ? <Loader2 className="size-4 animate-spin" /> : <FolderCheck className="size-4" />}Create draft source</Button></div></CardContent></Card>
      <Card className="evidence-panel evidence-panel-mint"><CardContent className="p-6"><div className="panel-title"><span className="panel-index">02</span><div><p className="eyebrow">Secure ingestion</p><h2>Add approved firm material</h2></div></div><p className="panel-intro">Only approved sources can be selected here. Supported: PDF, DOCX, XLS/XLSX, CSV, TXT, Markdown, and JSON. Limit: 12 MB.</p><div className="mt-5 grid gap-3"><div><Label>Approved source</Label><Select value={selectedSourceId} onValueChange={setSelectedSourceId}><SelectTrigger className="mt-1.5 bg-white"><SelectValue placeholder="Choose an approved source" /></SelectTrigger><SelectContent>{approvedSources.map(source => <SelectItem key={source.id} value={String(source.id)}>{source.name}</SelectItem>)}</SelectContent></Select></div><div><Label>Document title</Label><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="Use a clear, searchable title" className="mt-1.5 bg-white" /></div><div><Label>File</Label><Input ref={inputRef} type="file" accept=".pdf,.docx,.xlsx,.xls,.csv,.txt,.md,.json" onChange={event => setFile(event.target.files?.[0] ?? null)} className="mt-1.5 bg-white" />{file ? <p className="mt-1.5 text-[11px] text-[#4f715d]">{file.name} · {(file.size / 1024 / 1024).toFixed(2)} MB</p> : null}</div><Button onClick={submitUpload} disabled={!file || !selectedSourceId || upload.isPending} className="evidence-primary-button">{upload.isPending ? <Loader2 className="size-4 animate-spin" /> : <FileUp className="size-4" />}Upload and ingest</Button></div></CardContent></Card></div> : <Card className="evidence-notice"><CardContent><LockKeyhole className="size-4" />Source creation, approval, and document uploads are limited to administrators. You may use sources currently approved for your access level.</CardContent></Card>}
    <section className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Card className="evidence-register"><CardContent className="p-6"><div className="register-heading"><div><p className="eyebrow">Source register</p><h2>Knowledge boundaries</h2></div><span>{sources.data?.length ?? 0} total</span></div><div className="mt-4 space-y-2.5">{sources.data?.length ? sources.data.map(source => <article key={source.id} className="register-row"><div className="register-mark"><ScrollText className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p>{source.name}</p><Badge variant="outline" className={`text-[9px] capitalize ${approvalTone[source.approvalStatus]}`}>{source.approvalStatus}</Badge></div><p>{source.description || "No source purpose recorded."}</p><small>{source.classification} · {source.accessLevel === "all_users" ? "All firm users" : "Administrators only"}</small></div>{isAdmin && source.approvalStatus !== "archived" ? <div className="flex shrink-0 gap-1.5">{source.approvalStatus !== "approved" ? <Button variant="outline" size="sm" onClick={() => approval.mutate({ sourceId: source.id, status: "approved" })} className="h-7 text-[10px] text-[#367a51]"><CheckCircle2 className="mr-1 size-3" />Approve</Button> : <Button variant="ghost" size="sm" onClick={() => approval.mutate({ sourceId: source.id, status: "draft" })} className="h-7 text-[10px]">Draft</Button>}<Button variant="ghost" size="sm" onClick={() => approval.mutate({ sourceId: source.id, status: "archived" })} className="h-7 text-[10px] text-stone-500"><Archive className="mr-1 size-3" />Archive</Button></div> : null}</article>) : <EvidenceEmptyState icon={FolderCheck} eyebrow="No sources yet" title="Create the first evidence boundary." description="A source does not become searchable until its scope is reviewed and explicitly approved." steps={[{ label: "Create", detail: "Set a name, purpose, classification, and audience." }, { label: "Approve", detail: "A curator confirms the source is authoritative." }]} />}</div></CardContent></Card>
      <Card className="evidence-register"><CardContent className="p-6"><div className="register-heading"><div><p className="eyebrow">Ingestion register</p><h2>Document status</h2></div><FileClock className="size-4 text-[#478861]" /></div><div className="mt-4 space-y-2.5">{documents.data?.length ? documents.data.map(({ document, sourceName }) => <article key={document.id} className="register-row"><div className="register-mark"><FileClock className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-2"><p className="truncate">{document.title}</p><Badge variant="outline" className={`text-[9px] ${document.status === "ready" ? approvalTone.approved : document.status === "failed" ? "border-red-200 bg-red-50 text-red-700" : approvalTone.draft}`}>{document.status}</Badge></div><p>{sourceName} · {(document.byteSize / 1024).toFixed(0)} KB</p><small>{document.errorMessage || document.extractionSummary || "Awaiting secure processing."}</small></div></article>) : <EvidenceEmptyState icon={UploadCloud} eyebrow="No documents yet" title="The evidence register is ready." description="Ingestion results appear here, including the searchable state and any processing issue that needs review." steps={[{ label: "Select", detail: "Choose a curator-approved source." }, { label: "Ingest", detail: "Upload the approved file and confirm its state is Ready." }]} />}</div></CardContent></Card></section>
  </div>;
}
