import { useAuth } from "@/_core/hooks/useAuth";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Archive, CheckCircle2, ChevronRight, FileClock, FileText, FileUp, FolderPlus, Info, LockKeyhole, Loader2, ScrollText, UploadCloud } from "lucide-react";
import { useRef, useState } from "react";
import { toast } from "sonner";

const readFile = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(reader.error); reader.readAsDataURL(file); });
const maxBytes = 12 * 1024 * 1024;
const approvalTone: Record<string, string> = { approved: "border-emerald-300/30 bg-emerald-300/10 text-emerald-200", archived: "border-slate-400/25 bg-slate-400/10 text-slate-400", draft: "border-amber-300/35 bg-amber-300/10 text-amber-200" };
const statusTone: Record<string, string> = { ready: "border-emerald-300/30 bg-emerald-300/10 text-emerald-200", failed: "border-red-300/30 bg-red-300/10 text-red-200", processing: "border-cyan-300/30 bg-cyan-300/10 text-cyan-200" };

export default function Sources() {
  const { user } = useAuth();
  const isAdmin = user?.role === "admin";
  const utils = trpc.useUtils();
  const sources = trpc.knowledge.sources.list.useQuery();
  const documents = trpc.knowledge.documents.list.useQuery();
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [classification, setClassification] = useState<"internal" | "confidential" | "restricted">("internal");
  const [accessLevel, setAccessLevel] = useState<"all_users" | "admins_only">("all_users");
  const [selectedSourceId, setSelectedSourceId] = useState("");
  const [title, setTitle] = useState("");
  const [file, setFile] = useState<File | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);
  const refresh = () => { void utils.knowledge.sources.list.invalidate(); void utils.knowledge.documents.list.invalidate(); void utils.knowledge.workspace.invalidate(); };
  const createSource = trpc.knowledge.sources.create.useMutation({ onSuccess: () => { toast.success("Draft source created. Review and approve it before uploading."); setName(""); setDescription(""); refresh(); }, onError: error => toast.error(error.message) });
  const approval = trpc.knowledge.sources.setApproval.useMutation({ onSuccess: () => { toast.success("Source status updated."); refresh(); }, onError: error => toast.error(error.message) });
  const upload = trpc.knowledge.documents.upload.useMutation({ onSuccess: result => { result.status === "ready" ? toast.success(`${result.chunkCount} searchable passages are ready.`) : toast.error(result.errorMessage ?? "Document ingestion needs review."); setFile(null); setTitle(""); if (inputRef.current) inputRef.current.value = ""; refresh(); }, onError: error => toast.error(error.message) });
  const approvedSources = sources.data?.filter(source => source.approvalStatus === "approved") ?? [];
  const submitUpload = async () => { if (!file || !selectedSourceId) return toast.error("Choose an approved source and a file."); if (file.size > maxBytes) return toast.error("Files must be 12 MB or smaller."); try { upload.mutate({ sourceId: Number(selectedSourceId), title: title.trim() || file.name.replace(/\.[^.]+$/, ""), filename: file.name, mimeType: file.type || "application/octet-stream", base64: await readFile(file), metadata: { tags: [] } }); } catch { toast.error("The file could not be read."); } };

  return <div className="mx-auto max-w-[1480px] space-y-6">
    <section className="northstar-hero overflow-hidden rounded-[1.75rem] px-6 py-8 md:px-9"><div className="northstar-grid absolute inset-0 opacity-30" /><div className="relative flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div className="max-w-2xl"><p className="northstar-kicker">Knowledge governance</p><h1 className="mt-3 font-serif text-4xl leading-tight text-white md:text-5xl">Make the evidence boundary explicit.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-slate-200">Create a governed source, approve its scope, then upload the material Northstar is allowed to retrieve. Every document keeps a visible processing state.</p></div><div className="rounded-2xl border border-cyan-100/20 bg-[#091d26]/65 p-4 md:min-w-[250px]"><p className="text-[10px] font-bold uppercase tracking-[.14em] text-cyan-100/70">Current register</p><div className="mt-3 flex items-end gap-5"><div><p className="font-serif text-3xl text-white">{sources.data?.length ?? "—"}</p><p className="text-[10px] text-slate-400">sources</p></div><div><p className="font-serif text-3xl text-white">{documents.data?.length ?? "—"}</p><p className="text-[10px] text-slate-400">documents</p></div></div></div></div></section>

    {!isAdmin ? <section className="rounded-2xl border border-amber-300/30 bg-amber-300/10 p-4 text-sm text-amber-100"><div className="flex gap-3"><LockKeyhole className="mt-0.5 size-4 shrink-0" /><p><strong>Read-only access.</strong> Source creation, approval, and document uploads are limited to administrators. You can still use sources approved for your access level in Evidence Desk.</p></div></section> : null}

    {isAdmin ? <section className="grid gap-5 lg:grid-cols-2"><Card className="northstar-surface"><CardContent className="p-6"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl border border-cyan-200/25 bg-cyan-200/10 text-cyan-100"><FolderPlus className="size-5" /></div><div><p className="northstar-kicker">Step 1 · Define</p><h2 className="mt-2 font-serif text-2xl text-white">Create a source boundary</h2><p className="mt-2 text-sm leading-6 text-slate-400">Describe what belongs in this collection and who can retrieve it. New sources begin as drafts.</p></div></div><div className="mt-6 grid gap-4"><div><Label className="text-slate-200">Source name</Label><Input value={name} onChange={event => setName(event.target.value)} placeholder="Operations handbook" className="mt-1.5" /></div><div><Label className="text-slate-200">Purpose and content</Label><Textarea value={description} onChange={event => setDescription(event.target.value)} placeholder="What trusted material belongs in this boundary?" className="mt-1.5 min-h-24" /></div><div className="grid gap-3 sm:grid-cols-2"><div><Label className="text-slate-200">Classification</Label><Select value={classification} onValueChange={value => setClassification(value as typeof classification)}><SelectTrigger className="mt-1.5"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="internal">Internal</SelectItem><SelectItem value="confidential">Confidential</SelectItem><SelectItem value="restricted">Restricted</SelectItem></SelectContent></Select></div><div><Label className="text-slate-200">Audience</Label><Select value={accessLevel} onValueChange={value => setAccessLevel(value as typeof accessLevel)}><SelectTrigger className="mt-1.5"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all_users">All signed-in users</SelectItem><SelectItem value="admins_only">Administrators only</SelectItem></SelectContent></Select></div></div><Button onClick={() => createSource.mutate({ name, description, classification, accessLevel })} disabled={!name.trim() || createSource.isPending} className="northstar-primary h-11 gap-2">{createSource.isPending ? <Loader2 className="size-4 animate-spin" /> : <FolderPlus className="size-4" />}Create draft source<ChevronRight className="ml-auto size-4" /></Button></div></CardContent></Card>
      <Card className="northstar-surface"><CardContent className="p-6"><div className="flex items-start gap-3"><div className="grid size-10 shrink-0 place-items-center rounded-xl border border-amber-200/25 bg-amber-200/10 text-amber-100"><UploadCloud className="size-5" /></div><div><p className="northstar-kicker">Step 2 · Ingest</p><h2 className="mt-2 font-serif text-2xl text-white">Add firm material</h2><p className="mt-2 text-sm leading-6 text-slate-400">Upload into an approved boundary. Northstar extracts text, chunks it, and prepares it for hybrid retrieval.</p></div></div><div className="mt-6 rounded-xl border border-cyan-200/15 bg-cyan-200/5 p-3 text-xs leading-5 text-slate-300"><Info className="mr-2 inline size-3.5 text-cyan-200" />Supported: PDF, DOCX, XLS/XLSX, CSV, TXT, Markdown, and JSON. Maximum size: 12 MB.</div><div className="mt-4 grid gap-4"><div><Label className="text-slate-200">Approved source</Label><Select value={selectedSourceId} onValueChange={setSelectedSourceId}><SelectTrigger className="mt-1.5"><SelectValue placeholder="Choose an approved source" /></SelectTrigger><SelectContent>{approvedSources.map(source => <SelectItem key={source.id} value={String(source.id)}>{source.name}</SelectItem>)}</SelectContent></Select>{!approvedSources.length ? <p className="mt-2 text-xs text-amber-200">Approve a source in the register below before uploading.</p> : null}</div><div><Label className="text-slate-200">Document title <span className="font-normal text-slate-500">(optional)</span></Label><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="Uses the filename when blank" className="mt-1.5" /></div><div><Label className="text-slate-200">File</Label><Input ref={inputRef} type="file" accept=".pdf,.docx,.xlsx,.xls,.csv,.txt,.md,.json" onChange={event => setFile(event.target.files?.[0] ?? null)} className="mt-1.5" />{file ? <p className="mt-2 text-xs text-cyan-100">{file.name} · {(file.size / 1024 / 1024).toFixed(2)} MB</p> : null}</div><Button onClick={submitUpload} disabled={!file || !selectedSourceId || upload.isPending} className="northstar-primary h-11 gap-2">{upload.isPending ? <Loader2 className="size-4 animate-spin" /> : <FileUp className="size-4" />}Upload and ingest<ChevronRight className="ml-auto size-4" /></Button></div></CardContent></Card></section> : null}

    <section className="grid gap-5 lg:grid-cols-[1.1fr_.9fr]"><Card className="northstar-surface"><CardContent className="p-6"><div className="flex items-end justify-between gap-3"><div><p className="northstar-kicker">Step 3 · Govern</p><h2 className="mt-2 font-serif text-2xl text-white">Source register</h2><p className="mt-2 text-sm text-slate-400">Approve only boundaries that are authoritative and correctly scoped.</p></div><span className="text-xs text-slate-500">{sources.data?.length ?? 0} total</span></div><div className="mt-5 space-y-3">{sources.data?.length ? sources.data.map(source => <article key={source.id} className="rounded-xl border border-[#294652] bg-[#0e2029] p-4"><div className="flex items-start gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-[#17323e] text-cyan-100"><ScrollText className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-white">{source.name}</p><Badge variant="outline" className={`text-[9px] capitalize ${approvalTone[source.approvalStatus]}`}>{source.approvalStatus}</Badge></div><p className="mt-1 text-xs leading-5 text-slate-400">{source.description || "No source purpose recorded."}</p><p className="mt-2 text-[10px] font-semibold uppercase tracking-wide text-cyan-100/60">{source.classification} · {source.accessLevel === "all_users" ? "All firm users" : "Administrators only"}</p></div></div>{isAdmin && source.approvalStatus !== "archived" ? <div className="mt-3 flex flex-wrap justify-end gap-2 border-t border-[#294652] pt-3">{source.approvalStatus !== "approved" ? <Button variant="outline" size="sm" onClick={() => approval.mutate({ sourceId: source.id, status: "approved" })} className="h-8 gap-1.5 border-emerald-300/30 text-xs text-emerald-200 hover:bg-emerald-300/10"><CheckCircle2 className="size-3.5" />Approve</Button> : <Button variant="ghost" size="sm" onClick={() => approval.mutate({ sourceId: source.id, status: "draft" })} className="h-8 text-xs text-slate-300 hover:bg-[#17323e]">Move to draft</Button>}<Button variant="ghost" size="sm" onClick={() => approval.mutate({ sourceId: source.id, status: "archived" })} className="h-8 gap-1.5 text-xs text-red-200 hover:bg-red-400/10"><Archive className="size-3.5" />Archive</Button></div> : null}</article>) : <div className="rounded-xl border border-dashed border-[#35515f] p-6 text-center"><FolderPlus className="mx-auto size-6 text-cyan-200/70" /><p className="mt-3 font-semibold text-white">No source boundaries yet</p><p className="mt-1 text-xs leading-5 text-slate-400">Create the first source above, then approve its scope before adding documents.</p></div>}</div></CardContent></Card>
      <Card className="northstar-surface"><CardContent className="p-6"><div className="flex items-end justify-between gap-3"><div><p className="northstar-kicker">Ingestion register</p><h2 className="mt-2 font-serif text-2xl text-white">Document status</h2><p className="mt-2 text-sm text-slate-400">Processing messages stay visible so failures are actionable.</p></div><FileClock className="size-5 text-cyan-200" /></div><div className="mt-5 space-y-3">{documents.data?.length ? documents.data.map(({ document, sourceName }) => <article key={document.id} className="rounded-xl border border-[#294652] bg-[#0e2029] p-4"><div className="flex items-start gap-3"><div className="grid size-9 shrink-0 place-items-center rounded-lg bg-[#17323e] text-cyan-100"><FileText className="size-4" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><p className="truncate font-semibold text-white">{document.title}</p><Badge variant="outline" className={`shrink-0 text-[9px] capitalize ${statusTone[document.status] ?? approvalTone.draft}`}>{document.status}</Badge></div><p className="mt-1 text-xs text-slate-400">{sourceName} · {(document.byteSize / 1024).toFixed(0)} KB</p><p className="mt-2 text-[11px] leading-5 text-slate-300">{document.errorMessage || document.extractionSummary || "Awaiting secure processing."}</p></div></div></article>) : <div className="rounded-xl border border-dashed border-[#35515f] p-6 text-center"><UploadCloud className="mx-auto size-6 text-cyan-200/70" /><p className="mt-3 font-semibold text-white">No documents yet</p><p className="mt-1 text-xs leading-5 text-slate-400">Uploaded files and their searchable state will appear here.</p></div>}</div></CardContent></Card></section>
  </div>;
}
