import { useAuth } from "@/_core/hooks/useAuth";
import { EvidenceEmptyState } from "@/components/EvidenceEmptyState";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, Clock3, FilePenLine, Loader2, Send, ShieldAlert, UserCheck, X } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const statusStyle: Record<string, string> = { pending_approval: "border-amber-200 bg-amber-50 text-amber-700", approved: "border-emerald-200 bg-emerald-50 text-emerald-700", rejected: "border-red-200 bg-red-50 text-red-700", cancelled: "border-stone-200 bg-stone-50 text-stone-600" };
export default function Workflows() {
  const { user } = useAuth(); const utils = trpc.useUtils(); const isAdmin = user?.role === "admin"; const drafts = trpc.knowledge.workflows.list.useQuery();
  const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [draftType, setDraftType] = useState<"response" | "summary" | "record_update" | "other">("response"); const [targetSystem, setTargetSystem] = useState("");
  const create = trpc.knowledge.workflows.create.useMutation({ onSuccess: () => { toast.success("Draft is now awaiting human approval."); setTitle(""); setContent(""); setTargetSystem(""); void utils.knowledge.workflows.list.invalidate(); void utils.knowledge.workspace.invalidate(); }, onError: error => toast.error(error.message) });
  const review = trpc.knowledge.workflows.review.useMutation({ onSuccess: () => { toast.success("Review decision recorded. No external action was performed."); void utils.knowledge.workflows.list.invalidate(); void utils.knowledge.workspace.invalidate(); }, onError: error => toast.error(error.message) });
  return <div className="mx-auto max-w-[1200px] space-y-6"><section className="page-heading"><div><p className="eyebrow">Controlled workflow</p><h1>Drafts under human control</h1><p>This workspace can prepare work, but cannot send messages, alter records, or call an external system. Approval records a human decision only.</p></div><Badge className="evidence-warning-badge"><ShieldAlert className="mr-1.5 size-3" />All outputs are draft-only</Badge></section>
    <div className="grid gap-5 lg:grid-cols-[.86fr_1.14fr]"><Card className="evidence-panel evidence-panel-mint"><CardContent className="p-6"><div className="panel-title"><span className="panel-index">Draft</span><div><p className="eyebrow">Request review</p><h2>Create an internal draft</h2></div></div><p className="panel-intro">Create content from a reviewed answer or internal work item. A target system is only descriptive at this stage—this agent cannot write to it.</p><div className="mt-5 space-y-3"><div><Label>Draft title</Label><Input value={title} onChange={event => setTitle(event.target.value)} placeholder="Client response draft" className="mt-1.5 bg-white" /></div><div className="grid grid-cols-2 gap-3"><div><Label>Draft type</Label><Select value={draftType} onValueChange={value => setDraftType(value as typeof draftType)}><SelectTrigger className="mt-1.5 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="response">Response</SelectItem><SelectItem value="summary">Summary</SelectItem><SelectItem value="record_update">Record update proposal</SelectItem><SelectItem value="other">Other</SelectItem></SelectContent></Select></div><div><Label>Future target</Label><Input value={targetSystem} onChange={event => setTargetSystem(event.target.value)} placeholder="Optional, e.g. CRM" className="mt-1.5 bg-white" /></div></div><div><Label>Draft content</Label><Textarea value={content} onChange={event => setContent(event.target.value)} placeholder="Write or paste the internal-only draft here…" className="mt-1.5 min-h-44 bg-white" /></div><Button onClick={() => create.mutate({ title, draftType, content, targetSystem: targetSystem || undefined })} disabled={!title.trim() || !content.trim() || create.isPending} className="evidence-primary-button">{create.isPending ? <Loader2 className="size-4 animate-spin" /> : <Send className="size-4" />}Submit for human review</Button></div></CardContent></Card>
      <Card className="evidence-register"><CardContent className="p-6"><div className="register-heading"><div><p className="eyebrow">Decision ledger</p><h2>{isAdmin ? "All firm drafts" : "Your drafts"}</h2></div><span className="register-icon"><UserCheck className="size-4" /></span></div><div className="mt-4 space-y-3">{drafts.data?.length ? drafts.data.map(item => <article key={item.id} className="workflow-record"><div className="flex items-start justify-between gap-3"><div><p>{item.title}</p><small>{item.draftType.replace("_", " ")}{item.targetSystem ? ` · Future target: ${item.targetSystem}` : " · Internal only"}</small></div><Badge variant="outline" className={`text-[9px] ${statusStyle[item.status]}`}>{item.status.replace("_", " ")}</Badge></div><p className="workflow-content">{item.content}</p>{item.status === "pending_approval" && isAdmin ? <div className="mt-3 flex gap-2"><Button size="sm" onClick={() => review.mutate({ draftId: item.id, status: "approved", reviewerNote: "Reviewed by administrator. External action remains disabled." })} disabled={review.isPending} className="h-8 flex-1 bg-[#2e7650] text-[11px] hover:bg-[#235b3d]"><Check className="mr-1 size-3" />Approve draft</Button><Button variant="outline" size="sm" onClick={() => review.mutate({ draftId: item.id, status: "rejected", reviewerNote: "Returned for revision." })} disabled={review.isPending} className="h-8 flex-1 border-red-200 text-[11px] text-red-700 hover:bg-red-50"><X className="mr-1 size-3" />Return</Button></div> : null}{item.reviewerNote ? <p className="mt-2 text-[10px] leading-4 text-[#6e8173]"><strong>Review note:</strong> {item.reviewerNote}</p> : null}</article>) : <EvidenceEmptyState icon={Clock3} eyebrow="No review items" title="The decision ledger is clear." description="When a team member submits a draft, it enters here as pending approval. The reviewer can approve or return it, but no external action is triggered." steps={[{ label: "Draft", detail: "Prepare an internal-only output." }, { label: "Review", detail: "A named administrator records a decision." }, { label: "Use", detail: "A human takes any permitted action outside Atlas." }]} />}</div></CardContent></Card></div>
  </div>;
}
