export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  authProvider: process.env.AUTH_PROVIDER ?? "manus",
  oidcIssuerUrl: process.env.OIDC_ISSUER_URL ?? "",
  oidcClientId: process.env.OIDC_CLIENT_ID ?? process.env.VITE_APP_ID ?? "",
  oidcClientSecret: process.env.OIDC_CLIENT_SECRET ?? "",
  oidcScope: process.env.OIDC_SCOPE ?? "openid profile email",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  nodeEnv: process.env.NODE_ENV ?? "development",
  isProduction: process.env.NODE_ENV === "production",
  localAccessMode: process.env.NORTHSTAR_ACCESS_MODE ?? "",
  localNoAuth: process.env.NORTHSTAR_LOCAL_NO_AUTH === "true",
  localOperatorId: process.env.NORTHSTAR_LOCAL_OPERATOR_ID ?? "local-operator",
  localOperatorName: process.env.NORTHSTAR_LOCAL_OPERATOR_NAME ?? "Local Northstar Operator",
  // External-provider configuration is preferred. The legacy managed names remain
  // as a compatibility fallback until a deployment completes its migration.
  llmBaseUrl: process.env.OPENAI_BASE_URL ?? process.env.BUILT_IN_FORGE_API_URL ?? "",
  llmApiKey: process.env.OPENAI_API_KEY ?? process.env.BUILT_IN_FORGE_API_KEY ?? "",
  llmModel: process.env.LLM_MODEL ?? "gpt-4o-mini",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  storageEndpoint: process.env.S3_ENDPOINT ?? "",
  storageRegion: process.env.S3_REGION ?? "auto",
  storageBucket: process.env.S3_BUCKET ?? "",
  storageAccessKeyId: process.env.S3_ACCESS_KEY_ID ?? "",
  storageSecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? "",
  notificationWebhookUrl: process.env.NOTIFICATION_WEBHOOK_URL ?? "",
  notificationWebhookToken: process.env.NOTIFICATION_WEBHOOK_TOKEN ?? "",
};
